<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RootNamespace>Telematic.AssettoServer.Plugin</RootNamespace>
    <AssemblyName>Telematic.AssettoServer.Plugin</AssemblyName>
    <PathMap>$(MSBuildProjectDirectory)=Telematic.AssettoServer.Plugin</PathMap>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AssettoServer\AssettoServer.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime;native</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="..\AssettoServer\AssettoServer.Shared\AssettoServer.Shared.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime;native</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
